### ISSUE TITLE
Metal Press Gear Mold

### ISSUE THREAD

**Issue by Adamantion** [TheLimePixel/Crimson-Skies#44]
Seems like i can't make any gear, even the tinkers gear cast
Singleplayer, version 1.2.4.2

**Comment by ImelchorI** [comment]
have you tried just throwing 4 ingots on the conveyor of the metal press?

i have a hopper hooked up to the conveyor of the machine and noticed it seems to work with wire and plate molds just fine, but it doesnt insert the ingots when im trying to make gears.

for some reason i have to throw the 4 ingots to make a gear directly onto the conveyor myself instead of putting them into the hopper.
